apiVersion: batch/v1
kind: Job
metadata:
  labels:
    team: klage
    app: kaka-e2e-tests
  name: kaka-e2e-tests-{{jobid}}
  namespace: klage
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        team: klage
        app: kaka-e2e-tests
      annotations:
        linkerd.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccount: default
      serviceAccountName: default
      containers:
        - image: {{image}}
          name: kaka-e2e-tests
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: kaka-e2e-test-users
            - secretRef:
                name: slack-e2e-secrets
            - configMapRef:
                name: slack-e2e-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Never
